"""init insert permission table

Revision ID: 27a881adae7f
Revises: 6f9530f462f3
Create Date: 2023-09-11 00:25:39.367485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.db.orm import User
from app.db.permission import Role, Permission

# revision identifiers, used by Alembic.
revision: str = '27a881adae7f'
down_revision: Union[str, None] = '6f9530f462f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())

    User.create_permissions(session)
    Role.create_permissions(session)
    Permission.create_permissions(session)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())

    User.delete_permissions(session)
    Role.delete_permissions(session)
    Permission.delete_permissions(session)

    # ### end Alembic commands ###
